[package]
authors = ["Internet Security Research Group"]
name = "ppm-prototype"
version = "0.1.0"
edition = "2018"

[dependencies]
hpke = { version = "0.6.0", features = ["std", "x25519", "x25519-dalek", "p256"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = { version = "2.2.2", features = ["serde"] }
