[package]
authors = ["Internet Security Research Group"]
name = "ppm-prototype"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde", "std"] }
derivative = "2.1.1"
hpke = { path = "/home/timg/source/rust-hpke", features = ["std", "x25519", "p256", "serde_impls"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = { version = "2.2.2", features = ["serde"] }
